[project]
name = "replica-coinbase-api"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "fastapi[standard]",
  "pydantic-settings",
  "python-dotenv",
  "scikit-learn",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
